const{john,peter} = require('./2-names')
const { sayHi } = require('./5-utils')
const data = require('./4-alternative')
// console.log(names)
// console.log(sayHi)
console.log(data)
require('./3-mind-plus')
sayHi ('susan')
sayHi(john)
sayHi(peter)